from snakemake.utils import min_version

# set minimum snakemake version
min_version('8.16.0')

# parameters from the config file
configfile: 
    'config/config.yaml'

# environment variable
envvars:
    'comtrade_apikey'

# load rules
# include: 'rules/products_under_due_diligence.smk'
include: 'rules/hs_code_processing.smk'
include: 'rules/get_uncomtrade.smk'
# include: 'rules/get_faostat.smk'
# include: 'rules/corresponding_table.smk'
# include: 'rules/process_faostat_data.smk'
include: 'rules/data_preparation.smk'
# include: 'rules/aggregate_eu.smk'
# include: 'rules/group_bin.smk'

# target rule
rule all:
    input:
        'results/input/due_diligence_input.csv',
        'resources/public/due_diligence_data.parquet.gzip',
        'resources/public/placebo_data.parquet.gzip',
        'resources/inhouse/due_diligence_codes_hs6.csv',
        'resources/inhouse/placebo_codes_hs6.csv',
        # 'resources/public/uncomtrade.parquet.gzip',
        # 'resources/public/faostat.csv',
        # 'resources/inhouse/corresponding_table.csv',
        # 'results/input/input_faostat.csv',
        # 'results/intermediary/processed_faostat.csv',
        # 'results/input/input_uncomtrade.parquet.gzip',
        # 'results/input/input_uncomtrade_eu.parquet.gzip',
        # 'resources/inhouse/products_under_due_diligence.json'