from snakemake.utils import min_version

# set minimum snakemake version
min_version('8.16.0')

# parameters from the config file
configfile: 
    'config/config.yaml'

# environment variable
envvars:
    'comtrade_apikey'

# load rules
include: 'rules/get_uncomtrade.smk'
include: 'rules/get_faostat.smk'
include: 'rules/corresponding_table.smk'
include: 'rules/process_faostat_data.smk'
include: 'rules/filter_data.smk'
include: 'rules/aggregate_eu.smk'
# include: 'rules/group_bin.smk'

# target rule
rule all:
    input:
        'resources/public/uncomtrade.parquet.gzip',
        'resources/public/faostat.csv',
        'resources/inhouse/corresponding_table.csv',
        'results/input/input_faostat.csv',
        'results/intermediary/processed_faostat.csv',
        'results/input/input_uncomtrade.parquet.gzip',
        'results/input/input_uncomtrade_eu.parquet.gzip'