from snakemake.script import snakemake
import logging
import polars as pl
import polars.selectors as cs

# Log file edition
logging.basicConfig(filename=snakemake.log[0],
                    level=logging.INFO,
                    format='%(asctime)s %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S')

corr_policy_product_code = [

    {
        'policy': 'Lacey Act',
        'country': ('USA',),
        'iso_code': ('USA',),
        'year_signature': 1990,
        'year_implementation': 2008,
        'hs_heading': (4401,
                       4402,
                       4403,
                       4404,
                       4406,
                       4407,
                       4408,
                       4409,
                       441012,
                       4412,
                       441300,
                       4414,
                       4415,
                       441600,
                       441700,
                       4418,
                       4419,
                       4420,
                       4421,
                       940131,
                       940161,
                       940169,
                       940191,
                       940330,
                       940340,
                       940350,
                       940360,
                       940391,
                       940610,)
    },

    {
        'policy': 'Illegal Logging Prohibition Regulation',
        'country': ('Australia',),
        'iso_code': ('AUS',),
        'year_signature': 2012,
        'year_implementation': 2012,
        'hs_heading': (4403,
                       4407,
                       4408,
                       440910,
                       440922,
                       440929,
                       4410,
                       4411,
                       4412,
                       441300,
                       4414,
                       441600,
                       4418,
                       470100,
                       470200,
                       4703,
                       4704,
                       470500,
                       4801,
                       4802,
                       4803,
                       4804,
                       4805,
                       480620,
                       480630,
                       480640,
                       480700,
                       4808,
                       4809,
                       4810,
                       4811,
                       4813,
                       4816,
                       4817,
                       4818,
                       4819,
                       4820,
                       4821,
                       4823,
                       940161,
                       940169,
                       940330,
                       940340,
                       940350,
                       940360,
                       940391,
                       940610,)
    },

    {
        'policy': 'European Union Timber Regulation (EUTR)',
        'country': ('Austria', 
                    'Belgium',
                    'Belgium-Luxembourg (...1998)',
                    'Bulgaria',
                    'Croatia',
                    'Cyprus',
                    'Czechia',
                    'Denmark',
                    'Estonia',
                    'Finland',
                    'France',
                    'Germany',
                    'Greece',
                    'Hungary',
                    'Ireland',
                    'Italy',
                    'Latvia',
                    'Lithuania',
                    'Luxembourg',
                    'Malta',
                    'Netherlands',
                    'Poland',
                    'Portugal',
                    'Romania',
                    'Slovakia',
                    'Slovenia',
                    'Spain',
                    'Sweden',
                    'United Kingdom',),
        'iso_code': ('AUT',
                     'BEL',
                     'BGR',
                     'CYP',
                     'CZE',
                     'DEU',
                     'DNK',
                     'ESP',
                     'EST',
                     'FIN',
                     'FRA',
                     'GBR',
                     'GRC',
                     'HRV',
                     'HUN',
                     'IRL',
                     'ITA',
                     'LTU',
                     'LUX',
                     'LVA',
                     'MLT',
                     'NLD',
                     'POL',
                     'PRT',
                     'ROU',
                     'SVK', 
                     'SVN',
                     'SWE',),
        'year_signature': 2010,
        'year_implementation': 2013,
        'hs_heading': (4401,
                       4403,
                       4406,
                       4407,
                       4408,
                       4409,
                       4410,
                       4411,
                       4412,
                       441300,
                       4414,
                       4415,
                       441600,
                       4418,
                       47,
                       48,
                       940330,
                       940340,
                       940350,
                       940360,
                       940391,
                       940610,)
    },

    {
        'policy': 'Clean Wood Act',
        'country': ('Japan',),
        'iso_code': ('JPN',),
        'year_signature': 2016,
        'year_implementation': 2016,
        'hs_heading': (4403,
                       4407,
                       4410,
                       4411,
                       4412,
                       4408,
                       4401,
                       940161, 
                       940169, 
                       940330, 
                       940340, 
                       940350,
                       940360,
                       4701, 
                       4702, 
                       4703, 
                       4704, 
                       4705,
                       48,
                       4409, 
                       4418,)
    },

    {
        'policy': 'The Act on Sustainable Use of Timbers',
        'country': ('Rep. of Korea',),
        'iso_code': ('KOR',),
        'year_signature': 2018,
        'year_implementation': 2018,
        'hs_heading': (4403,
                       4407,
                       4412,
                       440131,)
    }
]

corr_policy_product_code_pl = pl.DataFrame(corr_policy_product_code)

logging.info(f"\nDataframe head: \n {corr_policy_product_code_pl} \n")
logging.info(f"\nDataframe size (rows, columns): {corr_policy_product_code_pl.shape} \n")

# Saving correspondence classification
corr_policy_product_code_pl.write_json(
    snakemake.output[0],
)
