# Years of trade
years:
  start: 1996
  stop: 2024  # process will consider stop year - 2 only

# HS codes --> products of interest
uncomtrade:
  cmdCode: [4403,    # Wood in the rough, whether or not stripped of bark or sapwood, or roughly squared. 
            4408,    # Sheets for veneering (including those obtained by slicing laminated wood), for plywood or for similar laminated wood and other wood, sawn lengthwise, sliced or peeled, whether or not planed, sanded, spliced or end-jointed, of a thickness not exceeding 6 mm. 
            4407,    # Wood sawn or chipped lengthwise, sliced or peeled, whether or not planed, sanded or end-jointed, of a thickness exceeding 6 mm. 
            4412,    # Plywood, veneered panels and similar laminated wood.
            4411,    # Fibreboard of wood or other ligneous materials, whether or not bonded with resins or other organic substances.
            441012,  # Oriented strand board (OSB) 
            47,      # Pulp of wood or of other fibrous cellulosic material; recovered (waste and scrap) paper or paperboard
            48       # Paper and paperboard; articles of paper pulp, of paper or of paperboard
          ]
  cmdDesc: ['Wood in the rough, whether or not stripped of bark or sapwood, or roughly squared.',
            'Sheets for veneering (including those obtained by slicing laminated wood), for plywood or for similar laminated wood and other wood, sawn lengthwise, sliced or peeled, whether or not planed, sanded, spliced or end-jointed, of a thickness not exceeding 6 mm.',
            'Wood sawn or chipped lengthwise, sliced or peeled, whether or not planed, sanded or end-jointed, of a thickness exceeding 6 mm.',
            'Plywood, veneered panels and similar laminated wood.',
            'Fibreboard of wood or other ligneous materials, whether or not bonded with resins or other organic substances.',
            'Oriented strand board (OSB)',
            'Pulp of wood or of other fibrous cellulosic material; recovered (waste and scrap) paper or paperboard',
            'Paper and paperboard; articles of paper pulp, of paper or of paperboard'
           ]

# Trade flows to download --> Imports, Exports
flowCode: ['M', 'X']

# FAO Item and Item codesfor products of interest
fao:
  items: ['Roundwood',
          'Veneer sheets',
          'Sawnwood',
          'Plywood and LVL',
          'Fibreboard',
          'Oriented strand board (OSB)',
          'Wood pulp',
          'Paper and paperboard']
  item_codes: [1861,
               1634,
               1872,
               1640,
               1874,
               1606,
               1875,
               1876]

# ISO code to exclude from analysis
excluded_iso: ['XX', '_X', '\d']
# This excludes the following non-country reporters or partners:
#    ['Southern African Customs Union (...1999)', 'Other Asia, nes',
#    'World', 'Areas, nes', 'Oceania, nes', 'Bunkers',
#    'Special Categories', 'Other Europe, nes', 'Other Africa, nes',
#    'Rest of America, nes', 'Free Zones', 'Western Asia, nes',
#    'CACM, nes', 'LAIA, nes', 'Caribbean, nes', 'Northern Africa, nes',
#    'North America and Central America, nes']

# Columns to keep for analysis (lighten computation)
col_keep:
  uncomtrade: ['period', 
               'reporterISO', 
               'reporterDesc', 
               'flowCode', 
               'partnerISO', 
               'partnerDesc',
               'cmdCode',  
               'netWgt', 
               'primaryValue']
  fao: ['Area Code (ISO3)',
        'Area',
        'Element',
        'Item Code',
        'Item',
        'Year',
        'Unit',
        'Value']

# Flow code to keep for analysis
flow_keep: ['M']

# List of EU countries and corresponding iso codes
eu:
  countries: ['Austria', 
              'Belgium',
              'Belgium-Luxembourg (...1998)',
              'Bulgaria',
              'Croatia',
              'Cyprus',
              'Czechia',
              'Denmark',
              'Estonia',
              'Finland',
              'France',
              'Germany',
              'Greece',
              'Hungary',
              'Ireland',
              'Italy',
              'Latvia',
              'Lithuania',
              'Luxembourg',
              'Malta',
              'Netherlands',
              'Poland',
              'Portugal',
              'Romania',
              'Slovakia',
              'Slovenia',
              'Spain',
              'Sweden',
              'United Kingdom']
  iso: ['AUT',
        'BEL',
        'BGR',
        'CYP',
        'CZE',
        'DEU',
        'DNK',
        'ESP',
        'EST',
        'FIN',
        'FRA',
        'GBR',
        'GRC',
        'HRV',
        'HUN',
        'IRL',
        'ITA',
        'LTU',
        'LUX',
        'LVA',
        'MLT',
        'NLD',
        'POL',
        'PRT',
        'ROU',
        'SVK', 
        'SVN',
        'SWE']

# List of risky countries and corresponding iso codes
risky: 
  countries: ['Brazil',
              'Cameroon',
              'China',
              'Congo',
              'Dem. Rep. of the Congo',
              'Ghana',
              'Indonesia',
              "Lao People's Dem. Rep.",
              'Malaysia',
              'Papua New Guinea',
              'Thailand',
              'Viet Nam']
  iso: ['BRA', 
        'CHN',
        'CMR',
        'COD',
        'COG',
        'GHA',
        'IDN',
        'LAO',
        'MYS',
        'PNG',
        'THA',
        'VNM']

# Year of implementation and country names/iso for each due diligence policy
policy:
  # USA Lacey Act
  lacey_act:
    year: 2008
    countries: ['USA']
    iso: ['USA']
  # Australian Illegal Logging Prohibition Act
  ilpa:
    year: 2012
    countries: ['Australia']
    iso: ['AUS']
  # European Union Timber Regulation
  eutr:
    year: 2013
    countries: ['Austria', 
                'Belgium',
                'Belgium-Luxembourg (...1998)',
                'Bulgaria',
                'Croatia',
                'Cyprus',
                'Czechia',
                'Denmark',
                'Estonia',
                'Finland',
                'France',
                'Germany',
                'Greece',
                'Hungary',
                'Ireland',
                'Italy',
                'Latvia',
                'Lithuania',
                'Luxembourg',
                'Malta',
                'Netherlands',
                'Poland',
                'Portugal',
                'Romania',
                'Slovakia',
                'Slovenia',
                'Spain',
                'Sweden',
                'United Kingdom']
    iso: ['AUT',
                    'BEL',
                    'BGR',
                    'CYP',
                    'CZE',
                    'DEU',
                    'DNK',
                    'ESP',
                    'EST',
                    'FIN',
                    'FRA',
                    'GBR',
                    'GRC',
                    'HRV',
                    'HUN',
                    'IRL',
                    'ITA',
                    'LTU',
                    'LUX',
                    'LVA',
                    'MLT',
                    'NLD',
                    'POL',
                    'PRT',
                    'ROU',
                    'SVK', 
                    'SVN',
                    'SWE']
  # Japanese Clean Wood Act
  cwa:
    year: 2016
    countries: ['Japan']
    iso: ['JPN']
  # South Korean Act of Sustainable Use of Timber
  asut:
    year: 2018
    countries: ['Rep. of Korea']
    iso: ['KOR']