# Years of trade
years:
  start: 1996
  stop: 2024  # process will consider stop year - 2 only

# Trade flows to download --> Imports, Exports
flowCode: ['M', 'X']

# ISO code to exclude from analysis
excluded_iso: ['XX', '_X', '\d']
# This excludes the following non-country reporters or partners:
#    ['Southern African Customs Union (...1999)', 'Other Asia, nes',
#    'World', 'Areas, nes', 'Oceania, nes', 'Bunkers',
#    'Special Categories', 'Other Europe, nes', 'Other Africa, nes',
#    'Rest of America, nes', 'Free Zones', 'Western Asia, nes',
#    'CACM, nes', 'LAIA, nes', 'Caribbean, nes', 'Northern Africa, nes',
#    'North America and Central America, nes']

# Columns to keep for analysis (lighten computation)
col_keep:
  uncomtrade: ['period', 
               'reporterISO', 
               'reporterDesc', 
               'flowCode', 
               'partnerISO', 
               'partnerDesc',
               'cmdCode',  
               'netWgt', 
               'primaryValue']
  fao: ['Area Code (ISO3)',
        'Area',
        'Element',
        'Item Code',
        'Item',
        'Year',
        'Unit',
        'Value']

# Flow code to keep for analysis
flow_keep: ['M']

# List of EU countries and corresponding iso codes
eu:
  countries: ['Austria', 
              'Belgium',
              'Belgium-Luxembourg (...1998)',
              'Bulgaria',
              'Croatia',
              'Cyprus',
              'Czechia',
              'Denmark',
              'Estonia',
              'Finland',
              'France',
              'Germany',
              'Greece',
              'Hungary',
              'Ireland',
              'Italy',
              'Latvia',
              'Lithuania',
              'Luxembourg',
              'Malta',
              'Netherlands',
              'Poland',
              'Portugal',
              'Romania',
              'Slovakia',
              'Slovenia',
              'Spain',
              'Sweden',
              'United Kingdom']
  iso: ['AUT',
        'BEL',
        'BGR',
        'CYP',
        'CZE',
        'DEU',
        'DNK',
        'ESP',
        'EST',
        'FIN',
        'FRA',
        'GBR',
        'GRC',
        'HRV',
        'HUN',
        'IRL',
        'ITA',
        'LTU',
        'LUX',
        'LVA',
        'MLT',
        'NLD',
        'POL',
        'PRT',
        'ROU',
        'SVK', 
        'SVN',
        'SWE']

# List of risky countries and corresponding iso codes
risky: 
  countries: ['Brazil',
              'Cameroon',
              'China',
              'Congo',
              'Dem. Rep. of the Congo',
              'Ghana',
              'Indonesia',
              "Lao People's Dem. Rep.",
              'Malaysia',
              'Papua New Guinea',
              'Thailand',
              'Viet Nam']
  iso: ['BRA', 
        'CHN',
        'CMR',
        'COD',
        'COG',
        'GHA',
        'IDN',
        'LAO',
        'MYS',
        'PNG',
        'THA',
        'VNM']

# Year of implementation and country names/iso for each due diligence policy
policy:
  # USA Lacey Act
  lacey_act:
    year: 2008
    countries: ['USA']
    iso: ['USA']
  # Australian Illegal Logging Prohibition Act
  ilpa:
    year: 2012
    countries: ['Australia']
    iso: ['AUS']
  # European Union Timber Regulation
  eutr:
    year: 2013
    countries: ['Austria', 
                'Belgium',
                'Belgium-Luxembourg (...1998)',
                'Bulgaria',
                'Croatia',
                'Cyprus',
                'Czechia',
                'Denmark',
                'Estonia',
                'Finland',
                'France',
                'Germany',
                'Greece',
                'Hungary',
                'Ireland',
                'Italy',
                'Latvia',
                'Lithuania',
                'Luxembourg',
                'Malta',
                'Netherlands',
                'Poland',
                'Portugal',
                'Romania',
                'Slovakia',
                'Slovenia',
                'Spain',
                'Sweden',
                'United Kingdom']
    iso: ['AUT',
                    'BEL',
                    'BGR',
                    'CYP',
                    'CZE',
                    'DEU',
                    'DNK',
                    'ESP',
                    'EST',
                    'FIN',
                    'FRA',
                    'GBR',
                    'GRC',
                    'HRV',
                    'HUN',
                    'IRL',
                    'ITA',
                    'LTU',
                    'LUX',
                    'LVA',
                    'MLT',
                    'NLD',
                    'POL',
                    'PRT',
                    'ROU',
                    'SVK', 
                    'SVN',
                    'SWE']
  # Japanese Clean Wood Act
  cwa:
    year: 2016
    countries: ['Japan']
    iso: ['JPN']
  # South Korean Act of Sustainable Use of Timber
  asut:
    year: 2018
    countries: ['Rep. of Korea']
    iso: ['KOR']